### ISSUE TITLE
Project installation

### ISSUE THREAD

**Issue by mboque50** [kevspadilla/docker-angular-zf2-gdrive#1]
Hello @kevspadilla ! 

I try run the project and I have this error : 

> Could not find module "@angular-devkit/build-angular" from "/Users/Mathieu/Decathlon/PHPProject/KevinPadilla/source/client/app".
> Error: Could not find module "@angular-devkit/build-angular" from "/Users/Mathieu/Decathlon/PHPProject/KevinPadilla/source/client/app".
>     at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
>     at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js:153:40)
>     at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
>     at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
>     at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:99:19
>     at new Promise (<anonymous>)
>     at Observable.toPromise (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:97:16)
>     at BuildCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:130:86)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

FYI I updated Node.js (v10.15.1) and I use Angular client v6 

I have this issue when I run: "ng build" 
Do you have an idea?

Thanks, 
Mathieu.

**Comment by kevspadillo** [comment]
Hi @mboque50,

I did not experience such issue when running ```ng build```. 

Try to run ```npm update``` or refer to this thread: https://stackoverflow.com/questions/50333003/could-not-find-module-angular-devkit-build-angular

I am running using Angular CLI 7.2.3 and Node 8.12.0.

I'll try to update my npm and angular cli. And will get back to you asap.


Hope it helps.

**Comment by kevspadillo** [comment]
@mboque50 , I tried to update my Node, npm and angular versions. And it works fine.

![image](https://user-images.githubusercontent.com/7956079/52116612-8a3af380-264c-11e9-9336-4de3e7a2dced.png)

**Comment by mboque50** [comment]
Hello @kevspadilla, 

Yes, it was that! `npm update ` 
I didn't run it for one-year ^^

Now, I have another error, I let you check that...
<img width="994" alt="capture d ecran 2019-02-02 a 10 44 21" src="https://user-images.githubusercontent.com/17120212/52158877-cbc4b080-26d7-11e9-8aee-fd05f383a371.png">

**Comment by kevspadillo** [comment]
Hi @mboque50,

Sorry i wasn't able to push my update.

Thanks for the catch, please kindly pull.

Thanks!

**Comment by mboque50** [comment]
It's work now. Well done!

I'm following the rest of the readme file.

**Comment by kevspadillo** [comment]
Awesome! 

I'll keep this issue open if you experience further issues.

Thanks!

**Comment by mboque50** [comment]
Hi @kevspadilla !

I did it ! I'm done with all yours steps. 

I have just a question, this is useful to do it ? 
`127.0.0.1 uploader-api.local`
`127.0.0.1 uploader-client.local`
This is the same IP.. same port. 

And unfortunalty, I tried to upload a file but I have nothing on my Google Drive and I have no error or log to tell me what happen.

**Comment by kevspadillo** [comment]
Hi @mboque50,

Yeps those are necessary, the applications are running inside a docker container and using virtualhosts in their corresponding web servers using those domains. 

And these host entries are used to point your local machine to the running containers.

**Comment by kevspadillo** [comment]
Hi @mboque50 ,

I pushed some updates in the Dockerfile of the api, kindly pull and rebuild the application by executing:

```
cd your_desired_project
docker-compose up --b
```

I increased the upload max filesize from 20M to 500M. I was not able to update this because most of my test pdf files are less than 20MB

Thanks!

**Comment by mboque50** [comment]
Hi @kevspadilla, 

Just to update you, thanks for your response and why hots file is important ;)
This is my log, an error 500
<img width="1476" alt="capture d ecran 2019-02-04 a 11 37 04" src="https://user-images.githubusercontent.com/17120212/52189078-5bea2d80-2871-11e9-9eab-f0c0c39408e1.png">

I will wait our call to continue.
